---
- hosts: localhost
  gather_facts: no

  roles:
    - { role: host-variable } # role::host-variable

- hosts: guest
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Login to MAAS
      command: "maas login {{maas_user}} {{maas_url}} {{maas_apikey}}"
      changed_when: false
      run_once: True
      delegate_to: "{{ maas_cli_srv }}" 
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - name: MAAS | DEVICES | check if device exists
      command: "maas {{ maas_user }} machines is-registered mac_address={{ dep_int_mac_address }}"
      changed_when: false
      delegate_to: "{{ maas_cli_srv }}"
      register: maas_devices_read
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - set_fact:
        machine_exists: "{{ maas_devices_read.stdout }}"
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - name: MAAS | DEVICES | check device status if device exists
      command: "maas {{ maas_user }} machines read mac_address={{ dep_int_mac_address }}"
      changed_when: false
      delegate_to: "{{ maas_cli_srv }}"
      register: maas_machine_state_read
      when: machine_exists|bool == true
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - set_fact:
        machine_state: "{{ maas_machine_state_read.stdout|from_json|json_query(query) }}"
      when: machine_exists|bool == true
      vars:
       query: "[0].status_name"
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - set_fact:
        host_system_id: "{{ maas_machine_state_read.stdout|from_json|json_query(query) }}"
      when: 
       - machine_exists|bool == true
      vars:
       query: "[0].system_id"
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

    - fail:  
        msg: "Device Already Exists && State is Deployed or Failed !!!"
      delegate_to: "{{ maas_cli_srv }}"
      when: ( machine_exists|bool == true and machine_state  == "Deployed" ) or ( machine_exists|bool == true and machine_state  == "Failed" ) 
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter

  roles:
    - { role: maas-configure-physical-server, when: server_state == 'physical' } # role::maas-configure-physical-server
    - { role: maas-add-device, when: machine_exists|bool == false } # role::maas-add-device
    - { role: maas-configure-net-int } # role::maas-configure-net-int
    - { role: maas-configure-storage-layout } # role::maas-configure-storage-layout
    - { role: maas-deploy-machine } # role::maas-deploy-machine
    - { role: maas-add-esxi-vcenter, when: distro == 'vmware' } # role::maas-add-esxi-vcenter 
    

  post_tasks:
    - name: Logout maas user
      command: maas logout {{maas_user}}
      changed_when: false
      run_once: True
      delegate_to: "{{ maas_cli_srv }}"
      tags:
        - role::maas-configure-physical-server
        - role::maas-add-device
        - role::maas-configure-net-int
        - role::maas-configure-storage-layout
        - role::maas-deploy-machine
        - role::maas-add-esxi-vcenter    
