---

    - name: Gather some info from a guest using the vSphere API output schema
      vmware_vm_info:
         hostname: "{{ vcenter_hostname }}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         validate_certs: no
         vm_type: vm
      register: vm_info

    - set_fact:
        vm_uuid: "{{ vm_info.virtual_machines|json_query(query) }}"
      vars:
        query: "[?guest_name=='{{ inventory_hostname }}'].uuid"

    - debug:
        msg: "Vmware {{ inventory_hostname }} UUID is: {{ vm_uuid[0] }}'"  

