---

    - name: MAAS | Add Devices
      command: |
            maas admin machines create \
            hostname={{ inventory_hostname }} \
            domain={{ domain }} \
            architecture=amd64/generic \
            mac_addresses={{ dep_int_mac_address }} \
            power_type=ipmi \
            power_parameters_power_driver='LAN_2_0 [IPMI 2.0]' \
            power_parameters_power_boot_type=Automatic \
            power_parameters_power_address={{ ilo_address }} \
            power_parameters_power_user={{ ilo_username }} \
            power_parameters_power_pass={{ ilo_password }} \
            zone={{ zone }}
      register: maas_devices_create

    - name: Wait for Commisioning State Complete
      action: command maas admin machines read hostname={{ inventory_hostname }}
      register: commisioningresult
      until: commisioningresult.stdout|from_json|json_query(query) == "Ready"
      retries: 60
      delay: 10
      vars:
       query: "[0].status_name"