---
  
  - name: Add ESXi Host to vCenter
    vmware_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter_name }}'
     #cluster: cluster_name
      esxi_hostname: '{{ pub_net_ip }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      state: present
    delegate_to: localhost