---
# tasks file for maas-deploy-machine

- import_tasks: 01-query-machine-deploy.yml
  delegate_to: "{{ maas_cli_srv }}"
  tags:
    - role::maas-deploy-machine
    - role::maas-deploy-machine::query-machine-deploy

- import_tasks: 02-deploy-machine.yml
  delegate_to: "{{ maas_cli_srv }}"
  tags:
    - role::maas-deploy-machine
    - role::maas-deploy-machine::deploy-machine