---
    - name: MAAS | DEVICES | check if device exists
      command: "maas {{ maas_user }} machines is-registered mac_address={{ dep_int_mac_address }}"
      changed_when: false
      delegate_to: "{{ maas_cli_srv }}"
      register: maas_devices_read
    

    - set_fact:
        machine_exists: "{{ maas_devices_read.stdout }}"


    - name: MAAS | DEVICES | check device status if device exists
      command: "maas {{ maas_user }} machines read mac_address={{ dep_int_mac_address }}"
      changed_when: false
      delegate_to: "{{ maas_cli_srv }}"
      register: maas_machine_state_read
      when: 
        - machine_exists|bool == true
        - machine_state is not defined or host_system_id is not defined

    - set_fact:
        machine_state: "{{ maas_machine_state_read.stdout|from_json|json_query(query) }}"
      when: 
        - machine_exists|bool == true
        - machine_state is not defined
      vars:
       query: "[0].status_name"


    - set_fact:
        host_system_id: "{{ maas_machine_state_read.stdout|from_json|json_query(query) }}"
      when: 
       - machine_exists|bool == true
       - host_system_id is not defined
      vars:
       query: "[0].system_id"


    


       