---

    - name: Fabric VLAN ID Check
      command: maas {{ maas_user }} fabrics read
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: public_fabric

    - set_fact:
        public_fabric_vlan_id: "{{ public_fabric.stdout|from_json|json_query(query) }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      vars:
        query: "[? name== '{{ public_fabric_name  }}' ].vlans[].id"

    - name: Host Network Interface Check
      command: maas {{ maas_user }} interfaces read {{ host_system_id }}
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: host_network_interface
      vars:
       query: "[0].status_name"

    - set_fact:
        int1_id: "{{ host_network_interface.stdout|from_json|json_query(query) }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      vars:
        query: "[? mac_address== '{{ pub_net1_mac_address }}' ].id"

    - set_fact:
        int2_id: "{{ host_network_interface.stdout|from_json|json_query(query) }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      vars:
        query: "[? mac_address== '{{ pub_net2_mac_address }}' ].id"


    - name: Network Interface I VLAN Config
      command: "maas admin interface update {{ host_system_id }} {{ int1_id[0] }}  vlan={{ public_fabric_vlan_id[0] }}"

    - name: Network Interface II VLAN Config
      command: "maas admin interface update {{ host_system_id }} {{ int2_id[0] }}  vlan={{ public_fabric_vlan_id[0] }}"

    - name: Create Bonding For Public Interface
      command: "maas admin interfaces create-bond  {{ host_system_id }} name=bond0 parents={{ int1_id[0] }} parents={{ int2_id[0] }} bond_mode={{ bond_mode }} bond_updelay=200 bond_downdelay=200 mtu=9000"
      when: machine_exists|bool == true and machine_state  == "Ready"
      vars:
        query: "[0].status_name"
      changed_when: false

    - name: Assign IP To Public Network Interface
      command: "maas admin interface link-subnet {{ host_system_id }} bond0 mode=static subnet={{ subnet }} ip_address={{ pub_net_ip }} force=true"
      when: machine_exists|bool == true and machine_state  == "Ready"
      vars:
       query: "[0].status_name"
      changed_when: false