---
  #### Guest Based Variables ####
  
  # Destination Server Network Config
  dep_int_mac_address : 00:50:56:83:49:5f
  # Domain
  domain: hpetrlab.local
  # Zone
  zone: HPE-TUR-LAB
  # Public Network Subnet:
  subnet: 10.254.254.0/24
  # Public Network IP Address
  pub_net_ip: 10.254.254.184
  # Public Network I MAC Address
  pub_net1_mac_address: 00:50:56:83:bc:97
  # Public Network II MAC Address
  pub_net2_mac_address: 00:50:56:83:79:b7


  ## Destination Server Storage Config (Size GB)
  boot_partition_size: 1
  boot_partition_format: fat32
  swap_partition_size: 4
  swap_partition_format: swap
  root_partition_size: 24
  root_partition_format: xfs
  var_partition_size: 8
  var_partition_format: xfs
  home_partition_size: 8
  home_partition_format: xfs
  tmp_partition_size: 8
  tmp_partition_format: xfs

  ## Deployed OS Version
  distro: rhel
  distro_version: 8.5

  ## Motherboard Firmware
  motherboard_firmware: bios

  ## Server State
  server_state: virtual

  ## HPE ILO Information
  ilo_address: 
  ilo_username: 
  ilo_password: 

  # OS Data Logical Drive
  OS_LogicalDriveName: OS
  OS_Raid: Raid1
  #Set to -1 to use all remaining space for maximum size
  OS_CapacityGiB: 120

