---

- name: Get Server Power Status
  uri:
    url: "https://{{ ilo_address }}/redfish/v1/Chassis?$expand=."
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ ilo_username }}"
    password: "{{ ilo_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: status

- set_fact:
    power-state: "{{ status.json.Members[0].PowerState }}"

- debug:
    msg: "Server Power State is: {{ power-state }}"

- name: Powered ON
  uri:
    url: "https://{{ ilo_address }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"On\"}"
    body_format: json
    validate_certs: no
    user: "{{ ilo_username }}"
    password: "{{ ilo_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  when: power-state == "Off"
  register: power

- debug:
    var=power.json.error
  when: power-state == "Off"

- name: Wait for Server Power State InPostDiscoveryComplete
  uri:
    url: "https://{{ ilo_address }}/redfish/v1/systems/1"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ ilo_username }}"
    password: "{{ ilo_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: poststate
  until: poststate.json.Oem.Hpe.PostState == "InPostDiscoveryComplete"
  retries: 20
  delay: 15
