---

    - name: Clean Storage Layout
      command: "maas {{maas_user}} machine set-storage-layout {{ host_system_id }} storage_layout=blank"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false


    - name: Check Block Device ID
      command: "maas {{maas_user}} block-devices read {{ host_system_id }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false
      register: maas_block_device_read

    - set_fact:
        block_device_id: "{{ maas_block_device_read.stdout|from_json|json_query(\"[? name=='sda'].id\") }}"
      when: machine_exists|bool == true and machine_state  == "Ready"