---

   - name: Define VMFS7 Storage Layout
     command: "maas {{maas_user}} machine set-storage-layout {{ host_system_id }} storage_layout=vmfs7"
     when: machine_exists|bool == true and machine_state  == "Ready"
     changed_when: false