---

    - name: Create Bootable Partition
      command: "maas {{maas_user}} partitions create {{ host_system_id }} {{ block_device_id[0] }} size={{ boot_partition_size }}G bootable=true"
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: bootable_partition

    - set_fact:
        boot_partition_id: "{{ bootable_partition.stdout|from_json|json_query('id') }}"
      when: machine_exists|bool == true and machine_state  == "Ready"

    - name: Configure EFI Partition
      block:

       - name: Create UEFI Boot Partition
         command: "maas {{maas_user}} partition format {{ host_system_id }} {{ block_device_id[0] }} {{ boot_partition_id }} fstype={{ boot_partition_format }}"
         changed_when: false
         register: efi_partition

       - name: Create UEFI Mount Point
         command: "maas {{maas_user}} partition mount {{ host_system_id }} {{ block_device_id[0] }} {{ boot_partition_id }} mount_point=/boot/efi"
         changed_when: false
         register: efi_mount_point

      when: 
        - motherboard_firmware == 'efi'
        - machine_exists|bool == true 
        - machine_state  == "Ready"

 #- name: Configure BIOS Partition
    #  block:
    #
    #   - name: Create  Boot Partition
    #     command: "maas {{maas_user}} partition format {{ host_system_id }} {{ block_device_id[0] }} {{ boot_partition_id }} fstype={{ boot_partition_format }}"
    #     changed_when: false
    #     register: boot_partition
    #
    #   - name: Create Boot Mount Point
    #     command: "maas {{maas_user}} partition mount {{ host_system_id }} {{ block_device_id[0] }} {{ boot_partition_id }} mount_point=/boot"
    #     changed_when: false
    #     register: boot_mount_point
    #
    #  when: 
    #    - motherboard_firmware == 'bios'
    #    - machine_exists == "exist" 
    #    - machine_state  == "Ready"