---

    - name: Create Root Logical Volumes
      command: "maas admin volume-group create-logical-volume {{ host_system_id }} {{ lvm_volume_group_id }} name=lv_root size={{ root_partition_size }}G"
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: root_logical_volume

    - set_fact:
        root_logical_volume_id: "{{ root_logical_volume.stdout|from_json|json_query('id') }}"
      when: machine_exists|bool == true and machine_state  == "Ready"

    - name: Format Root Filesystem
      command: "maas admin block-device format {{ host_system_id }} {{ root_logical_volume_id }} fstype={{ root_partition_format }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false

    - name: Mount Root Filesystem
      command: "maas admin block-device mount {{ host_system_id }} {{ root_logical_volume_id }} mount_point=/"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false