---

    - name: Create /var Logical Volumes
      command: "maas admin volume-group create-logical-volume {{ host_system_id }} {{ lvm_volume_group_id }} name=lv_var size={{ var_partition_size }}G"
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: var_logical_volume

    - set_fact:
        var_logical_volume_id: "{{ var_logical_volume.stdout|from_json|json_query('id') }}"
      when: machine_exists|bool == true and machine_state  == "Ready"

    - name: Format /var Filesystem
      command: "maas admin block-device format {{ host_system_id }} {{ var_logical_volume_id }} fstype={{ var_partition_format }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false

    
    - name: Mount /var Filesystem
      command: "maas admin block-device mount {{ host_system_id }} {{ var_logical_volume_id }} mount_point=/var"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false