---

    - name: Create /home Logical Volumes
      command: "maas admin volume-group create-logical-volume {{ host_system_id }} {{ lvm_volume_group_id }} name=lv_home size={{ home_partition_size }}G"
      changed_when: false
      when: machine_exists|bool == true and machine_state  == "Ready"
      register: home_logical_volume

    - set_fact:
        home_logical_volume_id: "{{ home_logical_volume.stdout|from_json|json_query('id') }}"
      when: machine_exists|bool == true and machine_state  == "Ready"

    - name: Format /home Filesystem
      command: "maas admin block-device format {{ host_system_id }} {{ home_logical_volume_id }} fstype={{ home_partition_format }}"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false

    
    - name: Mount /home Filesystem
      command: "maas admin block-device mount {{ host_system_id }} {{ home_logical_volume_id }} mount_point=/home"
      when: machine_exists|bool == true and machine_state  == "Ready"
      changed_when: false